/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace PlanRegistry {
      
    export type PlanStruct = {merchant: AddressLike, name: string, priceInCents: BigNumberish, currency: string, billingIntervalSeconds: BigNumberish, allowedTokens: AddressLike[], active: boolean}

    export type PlanStructOutput = [merchant: string, name: string, priceInCents: bigint, currency: string, billingIntervalSeconds: bigint, allowedTokens: string[], active: boolean] & {merchant: string, name: string, priceInCents: bigint, currency: string, billingIntervalSeconds: bigint, allowedTokens: string[], active: boolean }
  
    }

  export interface PlanRegistryInterface extends Interface {
    getFunction(nameOrSignature: "createPlan" | "getAllowedTokens" | "getMerchantPlanDetails" | "getMerchantPlans" | "getPlan" | "nextPlanId" | "owner" | "pauseAll" | "pausePlan" | "paused" | "plans" | "renounceOwnership" | "transferOwnership" | "unpauseAll" | "unpausePlan" | "updatePlan"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "Paused" | "PlanCreated" | "PlanPaused" | "PlanUnpaused" | "PlanUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'createPlan', values: [string, BigNumberish, string, BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'getAllowedTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMerchantPlanDetails', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMerchantPlans', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPlan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextPlanId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseAll', values?: undefined): string;
encodeFunctionData(functionFragment: 'pausePlan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'plans', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpauseAll', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpausePlan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updatePlan', values: [BigNumberish, string, BigNumberish, BigNumberish, AddressLike[], boolean]): string;

    decodeFunctionResult(functionFragment: 'createPlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllowedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMerchantPlanDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMerchantPlans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextPlanId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pausePlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'plans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpausePlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlan', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanCreatedEvent {
      export type InputTuple = [planId: BigNumberish, merchant: AddressLike];
      export type OutputTuple = [planId: bigint, merchant: string];
      export interface OutputObject {planId: bigint, merchant: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanPausedEvent {
      export type InputTuple = [planId: BigNumberish];
      export type OutputTuple = [planId: bigint];
      export interface OutputObject {planId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanUnpausedEvent {
      export type InputTuple = [planId: BigNumberish];
      export type OutputTuple = [planId: bigint];
      export interface OutputObject {planId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanUpdatedEvent {
      export type InputTuple = [planId: BigNumberish];
      export type OutputTuple = [planId: bigint];
      export interface OutputObject {planId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PlanRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): PlanRegistry;
    waitForDeployment(): Promise<this>;

    interface: PlanRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createPlan: TypedContractMethod<
      [name: string, priceInCents: BigNumberish, currency: string, billingIntervalSeconds: BigNumberish, allowedTokens: AddressLike[], ],
      [bigint],
      'nonpayable'
    >
    

    
    getAllowedTokens: TypedContractMethod<
      [planId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getMerchantPlanDetails: TypedContractMethod<
      [merchant: AddressLike, ],
      [PlanRegistry.PlanStructOutput[]],
      'view'
    >
    

    
    getMerchantPlans: TypedContractMethod<
      [merchant: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getPlan: TypedContractMethod<
      [planId: BigNumberish, ],
      [PlanRegistry.PlanStructOutput],
      'view'
    >
    

    
    nextPlanId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pauseAll: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    pausePlan: TypedContractMethod<
      [planId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    plans: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, boolean] & {merchant: string, name: string, priceInCents: bigint, currency: string, billingIntervalSeconds: bigint, active: boolean }],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpauseAll: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    unpausePlan: TypedContractMethod<
      [planId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updatePlan: TypedContractMethod<
      [planId: BigNumberish, name: string, priceInCents: BigNumberish, billingIntervalSeconds: BigNumberish, allowedTokens: AddressLike[], active: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createPlan'): TypedContractMethod<
      [name: string, priceInCents: BigNumberish, currency: string, billingIntervalSeconds: BigNumberish, allowedTokens: AddressLike[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllowedTokens'): TypedContractMethod<
      [planId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMerchantPlanDetails'): TypedContractMethod<
      [merchant: AddressLike, ],
      [PlanRegistry.PlanStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMerchantPlans'): TypedContractMethod<
      [merchant: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPlan'): TypedContractMethod<
      [planId: BigNumberish, ],
      [PlanRegistry.PlanStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'nextPlanId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pauseAll'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pausePlan'): TypedContractMethod<
      [planId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'plans'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, boolean] & {merchant: string, name: string, priceInCents: bigint, currency: string, billingIntervalSeconds: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpauseAll'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpausePlan'): TypedContractMethod<
      [planId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePlan'): TypedContractMethod<
      [planId: BigNumberish, name: string, priceInCents: BigNumberish, billingIntervalSeconds: BigNumberish, allowedTokens: AddressLike[], active: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PlanCreated'): TypedContractEvent<PlanCreatedEvent.InputTuple, PlanCreatedEvent.OutputTuple, PlanCreatedEvent.OutputObject>;
getEvent(key: 'PlanPaused'): TypedContractEvent<PlanPausedEvent.InputTuple, PlanPausedEvent.OutputTuple, PlanPausedEvent.OutputObject>;
getEvent(key: 'PlanUnpaused'): TypedContractEvent<PlanUnpausedEvent.InputTuple, PlanUnpausedEvent.OutputTuple, PlanUnpausedEvent.OutputObject>;
getEvent(key: 'PlanUpdated'): TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PlanCreated(uint256,address)': TypedContractEvent<PlanCreatedEvent.InputTuple, PlanCreatedEvent.OutputTuple, PlanCreatedEvent.OutputObject>;
      PlanCreated: TypedContractEvent<PlanCreatedEvent.InputTuple, PlanCreatedEvent.OutputTuple, PlanCreatedEvent.OutputObject>;
    

      'PlanPaused(uint256)': TypedContractEvent<PlanPausedEvent.InputTuple, PlanPausedEvent.OutputTuple, PlanPausedEvent.OutputObject>;
      PlanPaused: TypedContractEvent<PlanPausedEvent.InputTuple, PlanPausedEvent.OutputTuple, PlanPausedEvent.OutputObject>;
    

      'PlanUnpaused(uint256)': TypedContractEvent<PlanUnpausedEvent.InputTuple, PlanUnpausedEvent.OutputTuple, PlanUnpausedEvent.OutputObject>;
      PlanUnpaused: TypedContractEvent<PlanUnpausedEvent.InputTuple, PlanUnpausedEvent.OutputTuple, PlanUnpausedEvent.OutputObject>;
    

      'PlanUpdated(uint256)': TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
      PlanUpdated: TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }